[package]
name = "pincey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = { version = "0.3.0" }
tokio = { version = "1.4.0", features = ["rt-multi-thread"] } # for async in general