# fly.toml file generated for pincey on 2022-10-23T17:35:35-07:00

app = "pincey"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["paketo-community/rust"]

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true